apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090 # Prometheus exact URL; Grafana will take data from this URL
    isDefault: true # Make it the default dashboard

