name: 🐳 Build & Push Docker Image for docker-multistage-python

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    name: Build and Push Docker Image (docker-multistage-python)
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write  # GHCR push ke liye zaroori

    steps:
      # 1️⃣ Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2️⃣ Setup Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # 3️⃣ Login to GitHub Container Registry
      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # 4️⃣ Build Docker image
      - name: Build Docker image
        run: |
          IMAGE_NAME=ghcr.io/${{ github.repository_owner | toLower }}/docker-multistage-python
          cd docker-multistage-python
          docker build \
            -f Dockerfile \
            -t $IMAGE_NAME:latest \
            -t $IMAGE_NAME:${{ github.run_number }} \
            .

      # 5️⃣ Push image to GHCR
      - name: Push Docker image
        run: |
          IMAGE_NAME=ghcr.io/${{ github.repository_owner | toLower }}/docker-multistage-python
          docker push $IMAGE_NAME:latest
          docker push $IMAGE_NAME:${{ github.run_number }}

      # 6️⃣ Success message
      - name: Done
        run: echo "✅ Image for 'docker-multistage-python' pushed to GHCR successfully!"
