name: 🐳 Build & Push Docker Image for docker-multistage-python

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    name: Build and Push Docker Image (docker-multistage-python)
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker image
        run: |
          OWNER=$(echo "${{ github.repository_owner }}" | tr '[:upper:]' '[:lower:]')
          IMAGE_NAME=ghcr.io/$OWNER/docker-multistage-python
          cd docker-multistage-python
          docker build \
            -f Dockerfile \
            -t $IMAGE_NAME:latest \
            -t $IMAGE_NAME:${{ github.run_number }} \
            .

      - name: Push Docker image
        run: |
          OWNER=$(echo "${{ github.repository_owner }}" | tr '[:upper:]' '[:lower:]')
          IMAGE_NAME=ghcr.io/$OWNER/docker-multistage-python
          docker push $IMAGE_NAME:latest
          docker push $IMAGE_NAME:${{ github.run_number }}

      - name: Done
        run: echo "✅ Image for 'docker-multistage-python' pushed to GHCR successfully!"
